#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#  zipkin:
#    base-url: http://192.168.2.188:9411/
#  sleuth:
#    sampler:
#      probability: 1.0
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.2.188:8848
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          order: 1
#          predicates:
#            - Path=/user-server/**
#          filters:
#            - StripPrefix=1
#        - id: product-service
#          uri: lb://product-service
#          order: 1
#          predicates:
#            - Path=/product-server/**
#          filters:
#            - StripPrefix=1
#        - id: order-service
#          uri: lb://order-service
#          order: 1
#          predicates:
#            - Path=/order-server/**
#          filters:
#            - StripPrefix=1
#      discovery:
#        locator:
#          enabled: true
#logging:
#  level:
#    root: INFO
#    com.alibaba.nacos.client.config.impl: WARN